# Generated by Django 2.1 on 2018-10-11 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('logDate', models.DateField(null=True)),
                ('log_desc', models.CharField(default='----', max_length=1000)),
                ('log_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_name', models.CharField(max_length=100)),
                ('serverID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='serverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_logs.Server'),
        ),
    ]
